* evil-org

Evil extensions for Org-mode.

* Getting Started

** Moving around

=evil-org= aims to make motion in Org intuitive for Evil users,
so you can expect motions such as ~$~ to be similar to ~evil-end-of-line~,
~^~ to ~evil-first-non-blank~, and so on and so forth.

*** General motion

The following are the default motion bindings for =evil-org-motion=, use
~M-x describe-function BINDING~ for more information on each motion.

- ~gH~ :: ~evil-org-motion-up-heading-top~
- ~gh~ :: ~evil-org-motion-up-heading~
- ~{~  :: ~evil-org-motion-backward-heading~
- ~}~  :: ~evil-org-motion-forward-heading~

*** Tables

The following bindings apply when inside an Org table:

- ~gR~ :: ~evil-org-table-goto-line-from-bottom~
- ~gc~ :: ~evil-org-table-goto-column~
- ~gr~ :: ~evil-org-table-goto-line~
- ~|~  :: ~evil-org-table-goto-column~

** Operators

*** General Operators

The following are the default operator bindings for =evil-org-command=, use
~M-x describe-function BINDING~ for more information on each operator.

- ~<~ :: ~evil-org-promote~
- ~>~ :: ~evil-org-demote~

*** Table Operators

The following bindings apply when inside an Org table:

- ~<~ :: ~evil-org-table-move-column-left~
- ~>~ :: ~evil-org-table-move-column-right~
